/**
 * ComplianceFlow - Domain Enums & Constants
 */

export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum DepartmentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ComplianceType {
  LICENSE = 'LICENSE',
  PERMIT = 'PERMIT',
  CERTIFICATION = 'CERTIFICATION',
  POLICY = 'POLICY',
  TAX_FILING = 'TAX_FILING',
  AUDIT_REPORT = 'AUDIT_REPORT',
  CONTRACT = 'CONTRACT',
  OTHER = 'OTHER',
}

export enum ComplianceCategory {
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  SAFETY = 'SAFETY',
  FINANCIAL = 'FINANCIAL',
  LEGAL = 'LEGAL',
  OPERATIONAL = 'OPERATIONAL',
  IT_SECURITY = 'IT_SECURITY',
  HR = 'HR',
  OTHER = 'OTHER',
}

export enum ComplianceStatus {
  ACTIVE = 'ACTIVE',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  PENDING_RENEWAL = 'PENDING_RENEWAL',
  PROCESSING = 'PROCESSING',
  RENEWED = 'RENEWED',
  PENDING = 'PENDING',
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  IN_REVIEW = 'IN_REVIEW',
  NEARING_EXPIRY = 'NEARING_EXPIRY',
}

export enum RenewalFrequency {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUAL = 'SEMI_ANNUAL',
  ANNUAL = 'ANNUAL',
  BIENNIAL = 'BIENNIAL',
  TRIENNIAL = 'TRIENNIAL',
  CUSTOM = 'CUSTOM',
  NONE = 'NONE',
}

export enum PriorityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NotificationType {
  EXPIRY_WARNING = 'EXPIRY_WARNING',
  EXPIRED_ALERT = 'EXPIRED_ALERT',
  RENEWAL_REQUIRED = 'RENEWAL_REQUIRED',
  COMPLIANCE_ASSIGNED = 'COMPLIANCE_ASSIGNED',
  AUDIT_LOG = 'AUDIT_LOG',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

export enum DeliveryChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  BOTH = 'BOTH',
}

export enum EmailSentStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  DOWNLOAD = 'DOWNLOAD',
  RENEW = 'RENEW',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  STATUS_CHANGE = 'STATUS_CHANGE',
  VERIFY = 'VERIFY',
  VERIFY_QR = 'VERIFY_QR',
  DOCUMENT_RENEWED = 'DOCUMENT_RENEWED',
}

export enum AuditEntity {
  USER = 'USER',
  COMPANY = 'COMPANY',
  DEPARTMENT = 'DEPARTMENT',
  COMPLIANCE_RECORD = 'COMPLIANCE_RECORD',
  RENEWAL_RECORD = 'RENEWAL_RECORD',
  RENEWAL_HISTORY = 'RENEWAL_HISTORY',
  NOTIFICATION = 'NOTIFICATION',
  SYSTEM = 'SYSTEM',
}

export enum RenewalStatus {
  CREATED = 'CREATED',
  PENDING_RENEWAL = 'PENDING_RENEWAL',
  PROCESSING = 'PROCESSING',
  RENEWED = 'RENEWED',
  REQUESTED = 'REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
